annotations:
  category: Application
apiVersion: v2
appVersion: 4.5.3
description: Expertflow CX Solution
home: https://expertflow.com
icon: https://www.expertflow.com/wp-content/uploads/cropped-favicon-expertflow-32x32.png
keywords:
- Expertflow
- C2C Communications
maintainers:
- name: Nasir Mahmood Rajput 
  email: nasir.mehmood@expertflow.com
name: survey-backend
version: 1.0.0
