apiVersion: v1
kind: Secret
metadata:
  name: ef-gitlab-secret
  namespace: {{ .Release.Namespace }}
  labels:
    ef.app: expertflow-gitlab-access
    ef: expertflow
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "expertflow.imagePullSecret" . }}

