apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-efenvironment-cm
  namespace: {{ .Release.Namespace }}
data:
  {{- include "common.tplvalues.render" (dict "value" .Values.efEnvironmentVars  "context" $) | nindent 4 }}
