apiVersion: v2
name: artemis
description: Expertflow CX Solution ActiveMQ Artemis
home: https://expertflow.com
icon: https://www.expertflow.com/wp-content/uploads/cropped-favicon-expertflow-32x32.png
keywords:
  - Expertflow
  - C2C Communications
  - Artemis
type: application
version: "5.7.0"
appVersion: "5.7.0"
maintainers:
  - name: NMR Nasir Mehmood Rajput
    email: nasir.mehmood@expertflow.com
