# Default values for ef-cx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# ███████ ██   ██ ██████  ███████ ██████  ████████ ███████ ██       ██████  ██     ██ 
# ██       ██ ██  ██   ██ ██      ██   ██    ██    ██      ██      ██    ██ ██     ██ 
# █████     ███   ██████  █████   ██████     ██    █████   ██      ██    ██ ██  █  ██ 
# ██       ██ ██  ██      ██      ██   ██    ██    ██      ██      ██    ██ ██ ███ ██ 
# ███████ ██   ██ ██      ███████ ██   ██    ██    ██      ███████  ██████   ███ ███  
#
# Globals Section:
#
# global.ingressRouter: Provides a central location for the FQDN that will be used \
#                       across the EF CX solution
# global.registry: when deploying solution with limited access to internet, \
#                  changing this will cause all subsequent image pulls from this registry. \
#                  Used as Variable in all sub-charts
#


global:
  ingressRouter: "devops.ef.com"
  ingressCertName: "ef-ingress-tls-secret"
  ingressClassName: "nginx"
  efCxReleaseName: "ef-cx"
  commonIngressAnnotations: {}
  ##    nginx.ingress.kubernetes.io/rewrite-target: /$2
  ##    nginx.ingress.kubernetes.io/use-regex: "true"
  imageRegistry: "gitimages.expertflow.com"
  imagePullSecrets: 
   - ef-gitlab-secret
  ## The CommonEnvVars are now part of the globals. Selective adaption to components is mandatory.
  efCommonVars_IS_WRAP_UP_ENABLED: false
  efCommonVars_WRAPUP_TIME: "60"
  efCommonVars_DEFAULT_ROOM_NAME: CC
  efCommonVars_DEFAULT_ROOM_DESCRIPTION: Contact Center Room
  efCommonVars_DEFAULT_ROOM_LABEL: CC
  efCommonVars_ROOM_IS_USER_ID: false
  efCommonVars_CONVERSATION_SEARCH_WINDOW_HRS: "24"
  efCommonVars_TZ: UTC
  efCommonVars_MASK_ATTRIBUTES_PATH: /sensitive.js
  efCommonVars_LOGGING_CONFIG: /logback/logback-spring.xml
  efCommonVars_IS_ENABLED_2FA: "false"
  efCommonVars_CHANNEL_2FA: "app"
  efCommonVars_TWILIO_SID: ""
  efCommonVars_TWILIO_VERIFY_SID: ""
  efCommonVars_TWILIO_AUTH_TOKEN: ""
  efCommonVars_TOPIC_CONCURRENCY_MIN: "2"
  efCommonVars_TOPIC_CONCURRENCY_MAX: "6"

  ## EF-External related Service URIs -- not used atm. 
  efGrafanaDatasourceSecret: "ef-grafana-datasource-secret"
  efGrafanaSupervisorDashboardConfigMap: "ef-grafana-supervisor-dashboard-mysql"
  efGrafanaSupervisorDashboardFilename: "Supervisor_Dashboard_CIM-mysql.json"
  efGrafanaAgentDashboardConfigMap: "ef-grafana-agent-dashboard-mysql"
  efGrafanaAgentDashboardFilename: "Agent_Dashboard_CIM-mysql.json"
  efGrafanaDashboardDroviderCM: "ef-grafana-dashboard-provider-cm"
  efGrafanaIniCM: "ef-grafana-ini-cm"



clusterDomain: cluster.local


##############################unified-agent##############################
unified-agent:
   enabled: true
   replicaCount: 1
   image:       
      repository: cim/unified-agent
      tag: 4.7_f-CCC-1455
   efConnectionVars: true
   efEnvironmentVars: false
   containerPorts:
      - name: "http-un-ag-80"
        containerPort: 80
   extraEnvVars: []
   service:
      enabled: true
      port: 80
      portName: "http-un-ag-80"
      targetPort: "http-un-ag-80"
   ingress: 
      enabled: true 
      annotations:
         nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
         #cert-manager.io/cluster-issuer: "ef-letsencrypt-prod"
         nginx.ingress.kubernetes.io/rewrite-target: /$2
         nginx.ingress.kubernetes.io/use-regex: "true"
         nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers "Access-Control-Allow-Origin: $http_origin";'
         nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
         nginx.ingress.kubernetes.io/cors-allow-methods: 'PUT, GET, POST, OPTIONS, DELETE,PATCH'
         nginx.ingress.kubernetes.io/enable-cors: "true"
      path: /unified-agent(/|$)(.*)
      pathType: ImplementationSpecific
      ingressAssetsAnnotations:
         nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers "Access-Control-Allow-Origin: $http_origin";'
         nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
         nginx.ingress.kubernetes.io/cors-allow-methods: 'PUT, GET, POST, OPTIONS, DELETE,PATCH'
         nginx.ingress.kubernetes.io/enable-cors: "true"
   extraVolumes:
      - name: ef-app-translation
        configMap:
           name: ef-app-translations-cm
      - name: ef-crm-service
        configMap:
          name: ef-crm-service-cm
      - name: ef-canned-messages
        configMap:
          name: ef-canned-messages-cm
   extraVolumeMounts:
      - name: ef-app-translation
        mountPath: /usr/share/nginx/html/assets/i18n/
      - name: ef-crm-service
        mountPath: /usr/share/nginx/html/assets/cti/crm/
      - name: ef-canned-messages
        mountPath: /usr/share/nginx/html/assets/canned-messages/

grafana:
  enabled: true
  image:
    registry: gitimages.expertflow.com
    repository: general/grafana
    tag: 9-debian11.2
    pullPolicy: IfNotPresent
  dashboardsProvider:
    enabled: true
    configMapName: '{{ .Values.global.efGrafanaDashboardDroviderCM }}'
  dashboardsConfigMaps:
    - configMapName: '{{ .Values.global.efGrafanaSupervisorDashboardConfigMap }}'
      folderName: default
      fileName: '{{ .Values.global.efGrafanaSupervisorDashboardFilename }}'
    - configMapName: '{{ .Values.global.efGrafanaAgentDashboardConfigMap }}'
      folderName: default
      fileName: '{{ .Values.global.efGrafanaAgentDashboardFilename }}'
  datasources:
    secretName: "{{ .Values.global.efGrafanaDatasourceSecret }}"
  admin:
    user: "admin"
    password: "Expertflow123"
  config:
    useGrafanaIniFile: false
    grafanaIniConfigMap: "{{ .Values.global.efGrafanaIniCM }}"
  grafana:
    extraEnvVars:
      - name: GF_SERVER_DOMAIN
        value: "{{ .Values.global.ingressRouter }}"
      - name: GF_SERVER_ROOT_URL
        value: https://{{ .Values.global.ingressRouter }}/grafana
      - name: GF_SERVER_SERVE_FROM_SUB_PATH
        value: "true"
      - name: GF_SECURITY_ALLOW_EMBEDDING
        value: "true"
      - name: GF_AUTH.ANONYMOUS_ENABLED
        value: "true"
      - name: GF_AUTH_ANONYMOUS_ENABLED
        value: "true"
  ingress:
    enabled: true
    className: "{{ .Values.global.ingressClassName }}"
    pathType: ImplementationSpecific
    hostname: "{{ .Values.global.ingressRouter }}"
    path: /grafana(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      #cert-manager.io/cluster-issuer: "ef-letsencrypt-prod"
    tls: true
    extraTls:
       - hosts:
           -  '{{ .Values.global.ingressRouter }}'
         secretName: '{{ .Values.global.ingressCertName }}'


