# Default values for ef-cx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# ███████ ██   ██ ██████  ███████ ██████  ████████ ███████ ██       ██████  ██     ██ 
# ██       ██ ██  ██   ██ ██      ██   ██    ██    ██      ██      ██    ██ ██     ██ 
# █████     ███   ██████  █████   ██████     ██    █████   ██      ██    ██ ██  █  ██ 
# ██       ██ ██  ██      ██      ██   ██    ██    ██      ██      ██    ██ ██ ███ ██ 
# ███████ ██   ██ ██      ███████ ██   ██    ██    ██      ███████  ██████   ███ ███  
#
# Globals Section:
#
# global.ingressRouter: Provides a central location for the FQDN that will be used \
#                       across the EF CX solution
# global.registry: when deploying solution with limited access to internet, \
#                  changing this will cause all subsequent image pulls from this registry. \
#                  Used as Variable in all sub-charts
#


global:
  ingressRouter: "devops.ef.com"
  ingressCertName: "ef-ingress-tls-secret"
  ingressClassName: "nginx"
  efCxReleaseName: "ef-cx"
  commonIngressAnnotations: {}
  ##    nginx.ingress.kubernetes.io/rewrite-target: /$2
  ##    nginx.ingress.kubernetes.io/use-regex: "true"
  imageRegistry: "gitimages.expertflow.com"
  imagePullSecrets: 
   - ef-gitlab-secret
  ## The CommonEnvVars are now part of the globals. Selective adaption to components is mandatory.
  efCommonVars_IS_WRAP_UP_ENABLED: false
  efCommonVars_WRAPUP_TIME: "60"
  efCommonVars_DEFAULT_ROOM_NAME: CC
  efCommonVars_DEFAULT_ROOM_DESCRIPTION: Contact Center Room
  efCommonVars_DEFAULT_ROOM_LABEL: CC
  efCommonVars_ROOM_IS_USER_ID: false
  efCommonVars_CONVERSATION_SEARCH_WINDOW_HRS: "24"
  efCommonVars_TZ: UTC
  efCommonVars_MASK_ATTRIBUTES_PATH: /sensitive.js
  efCommonVars_LOGGING_CONFIG: /logback/logback-spring.xml
  efCommonVars_IS_ENABLED_2FA: "false"
  efCommonVars_CHANNEL_2FA: "app"
  efCommonVars_TWILIO_SID: ""
  efCommonVars_TWILIO_VERIFY_SID: ""
  efCommonVars_TWILIO_AUTH_TOKEN: ""
  efCommonVars_TOPIC_CONCURRENCY_MIN: "2"
  efCommonVars_TOPIC_CONCURRENCY_MAX: "6"

  ## EF-External related Service URIs -- not used atm. 
  efGrafanaDatasourceSecret: "ef-grafana-datasource-secret"
  efGrafanaSupervisorDashboardConfigMap: "ef-grafana-supervisor-dashboard"
  efGrafanaSupervisorDashboardFilename: "Supervisor_Dashboard_CIM.json"
  efGrafanaAgentDashboardConfigMap: "ef-grafana-agent-dashboard"
  efGrafanaAgentDashboardFilename: "Agent_Dashboard_CIM.json"
  efGrafanaDashboardProviderCM: "ef-grafana-dashboard-provider-cm"
  efGrafanaIniCM: "ef-grafana-ini-cm"


clusterDomain: cluster.local


##############################unified-agent##############################
unified-agent:
   enabled: true
   replicaCount: 1
   image:       
      repository: cim/unified-agent/build
      tag: "4.10.1"
   efConnectionVars: true
   efEnvironmentVars: false
   containerPorts:
      - name: "http-un-ag-80"
        containerPort: 80
   extraEnvVars:
      - name: TZ
        value: '{{ .Values.global.efCommonVars_TZ }}'
      - name: CONVERSATION_MANAGER_URL
        value: "https://{{ .Values.global.ingressRouter  }}/conversation-manager"
      - name: CIM_REPORTING_URL
        value: "https://{{ .Values.global.ingressRouter  }}/realtime-reports"
      - name: CIM_CUSTOMER_URL
        value: "https://{{ .Values.global.ingressRouter  }}/cim-customer"
      - name: UNIFIED_ADMIN_URL
        value: "https://{{ .Values.global.ingressRouter  }}/unified-admin"
      - name: CCM_URL
        value: "https://{{ .Values.global.ingressRouter  }}/ccm"
      - name: ROUTING_ENGINE_URL
        value: "https://{{ .Values.global.ingressRouter  }}/routing-engine"
      - name: TEAM_ANNOUNCEMENT_URL
        value: "https://{{ .Values.global.ingressRouter  }}/team-announcement"
      - name: getQueuesDelay
        value: "15"
      - name: bargeInType
        value: "BARGE_IN_CONSULT"
      - name: ssoBackendUrl
        value: "https://192.168.1.104:1123/"
      - name: isGadget
        value: "true"
      - name: silentMonitorType
        value: "SUPERVISOR_MONITOR"
      - name: ronaStateOnCisco
        value: "Call Not Answered"
      - name: ENV
        value: "prod"
      - name: FILE_SERVER_URL
        value: "https://{{ .Values.global.ingressRouter  }}/file-engine"
      - name: GAT_URL
        value: "https://{{ .Values.global.ingressRouter  }}/agent-manager"
      - name: GRAFANA_DASHBOARD_URL
        value: "https://{{ .Values.global.ingressRouter  }}/grafana/d/0GEdiaunk/cim-supervisor-dashboard?orgId=1&from=1655784727657&to=1655806327657"
      - name: SOCKET_URL
        value: "https://{{ .Values.global.ingressRouter  }}/agent-manager"
      - name: boshUrl
        value: "https://finesse12.ucce.ipcc:7443/http-bind/"
      - name: subBoshUrl
        value: "https://finesse.ucce.ipcc:7443/http-bind/"
      - name: callVariable
        value: "callVariable1"
      - name: conferenceType
        value: "CONFERENCE"
      - name: consultTransferTypeCCE
        value: "CONSULT_OFFERED"
      - name: consultTransferTypeCCX
        value: "TRANSFER"
      - name: consultType
        value: "CONSULT"
      - name: directTransferTypeCCE
        value: "TRANSFER"
      - name: directTransferTypeCCX
        value: "OFFERED"
      - name: directType
        value: "OTHER_IN"
      - name: domain
        value: "finesse12.ucce.ipcc"
      - name: subDomain
        value: "finesse12.ucce.ipcc"
      - name: ctiParam
        value: "U2FsdGVkX18ZqvnWRz7v3QJbCrEEQh7rNIPXqx8N39M="
      - name: ctiParam2
        value: "U2FsdGVkX18F8f3/3XmssO1QK8vCrmVje1z4HqCVrB0="
      - name: finesseFlavor
        value: "UCCX"
      - name: inboundTypeCCE
        value: "PREROUTE_ACD_IN"
      - name: inboundTypeCCX
        value: "ACD_IN"
      - name: outboundCampaignType
        value: "OUTBOUND"
      - name: outboundPreviewCampaignTypeCCE
        value: "OUTBOUND_PREVIEW"
      - name: outboundPreviewCampaignTypeCCX
        value: "OUTBOUND_DIRECT_PREVIEW"
      - name: outboundType
        value: "OUT"
      - name: outboundType2
        value: "AGENT_INSIDE"
      - name: isCiscoEnabled
        value: "false"
      - name: isCxVoiceEnabled
        value: "true"
      - name: CISCO_CC_MRD
        value: "20316843be924c8ab4f57a7a"
      - name: CX_VOICE_MRD
        value: "62f9e360ea5311eda05b0242"
      - name: SIP_SOCKET_URL
        value: "wss://192.168.1.17:7443"
      - name: SIP_URI
        value: "192.168.1.17"
      - name: EXT_STATIC
        value: "U2FsdGVkX1+YVwobqsio9pRiIEcB9FzpTYbnmzSDEm0="
      - name: ENABLE_SIP_LOGS
        value: "false"
      - name: STATIC_QUEUE_TRANSFER_DN
        value: "99887766"
      - name: AUTO_CALL_ANSWER_TIMER
        value: "2"
      - name: DASHBOARD_REFRESH_TIME
        value: "10000"
      - name: isCrmEventsEnabled
        value: "false"
      - name: SECURE_LINK_URL
        value: "https://{{ .Values.global.ingressRouter  }}/secure-link"
      - name: finesseURLForAgent
        value: "https://122.129.75.138:8445"
      - name: isSecureLinkEnabled
        value: "false"
      - name: Enable_Voice_Events_For_CRM
        value: "false"
      - name: IS_FINESSE_HA_ENABLED
        value: "false"
      - name: SECONDARY_FINESSE_URL
        value: "https://finesse12-5.ucce.ipcc:8445"
      - name: CISCO_SERVICE_IDENTIFIER
        value: "0000"
      - name: SIP_MONITORING_DN
        value: "*44"
      - name: SIP_EXTERNAL_DN
        value: "99887765"
      - name: AUTO_ANSWER_DELAY
        value: "5000"
      - name: SOCKET_TIMEOUT
        value: "20000"
      - name: IS_WEBRTC_VIDEO_ENABLED
        value: "false"
      - name: WEBRTC_SERVICE_IDENTIFIER
        value: "00000"
      - name: isSpellCheckEnabled
        value: "true"
   siteEnvVars: []
   configKeys: []
   service:
      enabled: true
      port: 80
      portName: "http-un-ag-80"
      targetPort: "http-un-ag-80"
   ingress:
      enabled: false
      ingressAssets:
        enabled: false
        annotations: {}
        path: /assets
   extraVolumes:
      - name: ef-app-translation
        configMap:
           name: ef-app-translations-cm
      - name: ef-crm-service
        configMap:
          name: ef-crm-service-cm
      - name: ef-canned-messages
        configMap:
          name: ef-canned-messages-cm
   extraVolumeMounts:
      - name: ef-app-translation
        mountPath: /usr/share/nginx/html/assets/i18n/
      - name: ef-crm-service
        mountPath: /usr/share/nginx/html/assets/cti/crm/
      - name: ef-canned-messages
        mountPath: /usr/share/nginx/html/assets/canned-messages/

grafana:
  enabled: true
  image:
    registry: gitimages.expertflow.com
    repository: general/grafana
    tag: 9-debian11.2
    pullPolicy: IfNotPresent
  dashboardsProvider:
    enabled: true
    configMapName: '{{ .Values.global.efGrafanaDashboardProviderCM }}'
  dashboardsConfigMaps:
    - configMapName: '{{ .Values.global.efGrafanaSupervisorDashboardConfigMap }}'
      folderName: default
      fileName: '{{ .Values.global.efGrafanaSupervisorDashboardFilename }}'
    - configMapName: '{{ .Values.global.efGrafanaAgentDashboardConfigMap }}'
      folderName: default
      fileName: '{{ .Values.global.efGrafanaAgentDashboardFilename }}'
  datasources:
    secretName: "{{ .Values.global.efGrafanaDatasourceSecret }}"
  admin:
    user: "admin"
    password: "Expertflow123"
  config:
    useGrafanaIniFile: false
    grafanaIniConfigMap: "{{ .Values.global.efGrafanaIniCM }}"
  grafana:
    extraEnvVars:
      - name: GF_SERVER_DOMAIN
        value: "{{ .Values.global.ingressRouter }}"
      - name: GF_SERVER_ROOT_URL
        value: https://{{ .Values.global.ingressRouter }}/grafana
      - name: GF_SERVER_SERVE_FROM_SUB_PATH
        value: "true"
      - name: GF_SECURITY_ALLOW_EMBEDDING
        value: "true"
      - name: GF_AUTH.ANONYMOUS_ENABLED
        value: "true"
      - name: GF_AUTH_ANONYMOUS_ENABLED
        value: "true"
  ingress: { enabled: false } # Disabled in favor of APISIX
