{{- if .Values.ciscoTeamSynchronizerCronJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "common.names.fullname" . }}-cron
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if or .Values.ciscoTeamSynchronizerCronJob.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.ciscoTeamSynchronizerCronJob.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ciscoTeamSynchronizerCronJob.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  schedule: {{ quote .Values.ciscoTeamSynchronizerCronJob.schedule }}
  concurrencyPolicy: {{ .Values.ciscoTeamSynchronizerCronJob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.ciscoTeamSynchronizerCronJob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.ciscoTeamSynchronizerCronJob.successfulJobsHistoryLimit }}
  {{- if .Values.ciscoTeamSynchronizerCronJob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.ciscoTeamSynchronizerCronJob.startingDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    spec:
      {{- if .Values.ciscoTeamSynchronizerCronJob.backoffLimit }}
      backoffLimit: {{ .Values.ciscoTeamSynchronizerCronJob.backoffLimit }}
      {{- end }}
      {{- if .Values.ciscoTeamSynchronizerCronJob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.ciscoTeamSynchronizerCronJob.ttlSecondsAfterFinished }}
      {{- end }}
      template:
        metadata:
          labels: {{- include "common.labels.standard" . | nindent 12 }}
            {{- if .Values.ciscoTeamSynchronizerCronJob.labels }}
            {{- include "common.tplvalues.render" (dict "value" .Values.ciscoTeamSynchronizerCronJob.labels "context" $) | nindent 12 }}
            {{- end }}
            {{- if .Values.commonLabels }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 12 }}
            {{- end }}
          {{- if or .Values.ciscoTeamSynchronizerCronJob.annotations .Values.commonAnnotations }}
          annotations:
            {{- if .Values.ciscoTeamSynchronizerCronJob.annotations }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.ciscoTeamSynchronizerCronJob.annotations "context" $) | nindent 12 }}
            {{- end }}
            {{- if .Values.commonAnnotations }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 12 }}
            {{- end }}
          {{- end }}
        spec:
          imagePullSecrets:
             - name: {{ .Values.ciscoTeamSynchronizerCronJob.imagePullSecret }}
          containers:
          - name: {{ include "common.names.fullname" . }}-cron
            image: {{ .Values.ciscoTeamSynchronizerCronJob.image }}
            imagePullPolicy: IfNotPresent
            env:
            {{- if .Values.ciscoTeamSynchronizerCronJob.extraEnvVars }}
               {{- include "common.tplvalues.render" (dict "value" .Values.ciscoTeamSynchronizerCronJob.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
            {{- if .Values.ciscoTeamSynchronizerCronJob.command }}
            command: {{- include "common.tplvalues.render" (dict "value" .Values.ciscoTeamSynchronizerCronJob.command "context" $) | nindent 14 }}
            {{- end }}
            {{- if .Values.ciscoTeamSynchronizerCronJob.resources }}
            resources: {{- include "common.tplvalues.render" (dict "value" .Values.ciscoTeamSynchronizerCronJob.resources "context" $) | nindent 14 }}
            {{- else if ne .Values.ciscoTeamSynchronizerCronJob.resourcesPreset "none" }}
            resources: {{- include "common.resources.preset" (dict "type" .Values.ciscoTeamSynchronizerCronJob.resourcesPreset) | nindent 14 }}
            {{- end }}
            {{- if .Values.ciscoTeamSynchronizerCronJob.containerSecurityContext.enabled }}
            securityContext:
              {{- include "common.tplvalues.render" ( dict "value" ( omit .Values.ciscoTeamSynchronizerCronJob.containerSecurityContext "enabled" ) "context" $) | nindent 14 }}
            {{- end }}
            {{- if .Values.ciscoTeamSynchronizerCronJob.extraVolumeMounts }}
            volumeMounts:
              {{- include "common.tplvalues.render" ( dict "value" .Values.ciscoTeamSynchronizerCronJob.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
          restartPolicy: {{ .Values.ciscoTeamSynchronizerCronJob.restartPolicy }}
          volumes:
          {{- if .Values.ciscoTeamSynchronizerCronJob.extraVolumes }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.ciscoTeamSynchronizerCronJob.extraVolumes "context" $) | nindent 12 }}
          {{- end }}
{{- end }}
