
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: expertflow
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: default
      containers:
      - image: jweissig/app:0.0.1
        name: webapp
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appname-secret
              key: password
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: appname-secret
              key: username
        - name: DB_TOKEN
          valueFrom:
            secretKeyRef:
              name: appname-secret
              key: token
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "vault-appname"

