kind: Pod
apiVersion: v1
metadata:
  name: webapp-2
  namespace: expertflow
spec:
  serviceAccountName: default
  containers:
  - image: jweissig/app:0.0.1
    name: webapp
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: appname-2-secret
          key: password
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: appname-2-secret
          key: username
    - name: DB_TOKEN
      valueFrom:
        secretKeyRef:
          name: appname-2-secret
          key: token
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-appname-2"
