image:
  registry: gitimages.expertflow.com
  repository: general/redis
  tag: CIM-4292-6.2-debian-10-k8s
  pullSecrets:
    - expertflow-reg-cred
architecture: standalone
auth:
  enabled: true
  sentinel: true
  password: "Expertflow123"

commonConfiguration: |-
  appendonly yes
  save ""
##


master:
  count: 1
  disableCommands: []
  extraFlags:
    - '--loadmodule /opt/bitnami/redis/modules/rejson.so'
    - '--loadmodule /opt/bitnami/redis/modules/redisearch.so'
  startupProbe:
    enabled: false
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  resources:
    limits:
      cpu: 250m
      memory: 2Gi
    requests:
      cpu: 150m
      memory: 1Gi
  kind: StatefulSet
  initContainers:
      - name: ef-set-sysctl
        image: busybox
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          sysctl -w net.core.somaxconn=65535
          sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sysctl -w net.ipv4.tcp_tw_reuse=1
          sysctl -w fs.file-max=1048576
          sysctl -w net.ipv4.tcp_rmem="4096 26214400 26214400" || true

  ##
  persistence:
    enabled: true
    size: 4Gi
sentinel:
  enabled: false

##
tls:
  enabled: true
  authClients: true
  autoGenerated: false
  existingSecret: "redis-crt"
  certificatesSecret: ""
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
  certCAFilename: "ca.crt"
  dhParamsFilename: ""

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
