# Default values for ef-cx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# ███████ ██   ██ ██████  ███████ ██████  ████████ ███████ ██       ██████  ██     ██
# ██       ██ ██  ██   ██ ██      ██   ██    ██    ██      ██      ██    ██ ██     ██
# █████     ███   ██████  █████   ██████     ██    █████   ██      ██    ██ ██  █  ██
# ██       ██ ██  ██      ██      ██   ██    ██    ██      ██      ██    ██ ██ ███ ██
# ███████ ██   ██ ██      ███████ ██   ██    ██    ██      ███████  ██████   ███ ███
#

global:
   efCxReleaseName: "ef-cx"
   ingressRouter: devops.ef.com

####################### Reporting Connector CronJob Definitions ######################
reportingConnectorCronJob:
   enabled: true
   labels: {}
   containerSecurityContext:
     enabled: false
     seLinuxOptions: {}
     runAsUser: 1001
     runAsGroup: 1001
     runAsNonRoot: true
     privileged: false
     readOnlyRootFilesystem: true
     allowPrivilegeEscalation: false
     capabilities:
       drop: ["ALL"]
     seccompProfile:
       type: "RuntimeDefault"
   annotations: {}
   schedule: "*/5 * * * *"
   failedJobsHistoryLimit: 1
   successfulJobsHistoryLimit: 5
   startingDeadlineSeconds: 20
   concurrencyPolicy: "Forbid"
   backoffLimit: 0
   restartPolicy: OnFailure
   imagePullSecret: ef-gitlab-secret
   image: gitimages.expertflow.com/cim/reporting-connector:4.6.1_f-CIM-27184
   extraEnvVars: []
   resourcesPreset: "none"
   resources: {}
   extraVolumeMounts: 
      - name: reporting-connector-config
        mountPath: /root/config/reporting-connector.conf
        subPath: reporting-connector.conf
      - name: ef-reporting-connector-keystore
        mountPath: /root/config/certs/mykeystore.jks
        subPath: mykeystore.jks
      - name: mongo-mongodb-ca
        mountPath: /mongo
   extraVolumes: 
      - name: ef-reporting-connector-keystore
        configMap:
          name: ef-reporting-connector-keystore-cm
          optional: true
      - name: reporting-connector-config
        configMap:
          name: ef-reporting-connector-conf-cm
          optional: true
      - name: mongo-mongodb-ca
        secret:
          secretName: mongo-mongodb-ca

